apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-self-signed-ca-cert
spec:
  isCA: true
  commonName: *.tor01.containers.appdomain.cloud
  secretName: mq-self-signed-ca-cert
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
