kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tools-tekton
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tools-tekton
