apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/operators/sealed-secrets
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: rosa-useast-mq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
