apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAkeIIFuhBwBFCHlC1ybcHDsPQi5uYUXP/nZ8ZWiznArQeWosn7AbFn5LCrqIDxn9PX8CMyqyc62MYAw4sGURPOZYGEbdBcEMwuYkLwRdiXqkxDVC3CHTpKLqaLfaBG584xQLpMfjvC2cqV3d+73+7avbibFSjHqdOWS9Be+/281qFHaa7g5FjhusJpWwxptRMqNsKraX1bQUP4vdqNdu1L1+LDDFu+mm7db/6fyblUyqGcDOGMrDnO0QtpHei+dPj94WWhj2F88776/cfQNR7z1M62izRlBWt0whuop2o8psH9pRSGyAXYMqZnrgoX7yj7jnUQGZ5X+t1VwzOKqVpfbmH/jglsnwcqk0VlLIRdUhA/vExq5G0tOlHlbMh5BIoqOynlH3X+w8AQ8hvtN+IAczsVGBs6SgLWWrXIPJK9L05bPPaN5LfAiS9OnWTdzD4geF7CTmtdbzLfcqKq75MWAYEGQ2bD9NAaNyA59BCSfpUuLLWELjqiN48h6KDCCI+D7i6G7D5mGQkEK9bB19iDfvHIbX9wGgZ9rCFsz9FGzV5lDJW01UY5WCH3KXzkqpwuH9Pai9guSfiWUZAIzITxZ1FgpgamOJHOI+Jaqc/rX+Z83uPRWlVGI2+5VNUaMV8IX5DZH7o3Fd8Cg9azVcL5lIxhpSULYfVjhtHv4tU8wZwjWsLvALMTz61dmj8mNS6TMOucrPRG2qTp2PtsGgAyirUd+ou3AmhwDLEdwMITzUAgSnO2wTkrjhG2i8vlO2jv2CsECje2bByPKL32oTJrYnNtXBJb6z0pQTWwlJFIT+swqO80YJWGLz+P36LXQXi/yH2G/Je/nhhb+YUR57oIAobGbP4qQlqpYpNenDweC1TxAEJk8QcaYnXCqF/fC5ZNiLAaR0E1WSwewc5Zc2l0Q2AOZpFsE5gPCZNAVdg3ow==
    IBM_ENTITLED_REGISTRY_USER: AgASTRArrH8bT6ExpAAC+AQ2kNB5yYcCS/1OsABFqDeB6GixJJwwlzYGzY3BWR0/YF0eUvauOXfXqfMrtAIPPIT1OjTqlLvMoGJvFoVTevC/Ixu0s14iLpxvFHnw0FLIZ87KeLEz1yw4+LT+DmoXBeVF+ODxfCTkf1WBVeyww+7x3UqI4IXlp78VQ3fssCjwYctvmb2TaV9/VDMlht2/8oCt/fDIfGQzwY9Ul8cR7J5N5weLAKtKteVEJ1Fg8zIE2ipwobbtgIpGJJLgghIfHrKHcUleWAc/qmGC676xZUayEgA8C0BTsom50lqDBpka2rfeAvRlZfdqBifCUDa1ChGHgLjsIU/jMYBsnBSCd1igBlVNRZlc2tgaa4U6Lvqi5YCdozgwGOHVcL22/RTiJRN/0BMtqGJk9XMstIW11yOtWvx2GxD5GZ9rK8Hr/prhhvk/zSBw2b5U2bGbpa6fiQ5ID5UypLTv0MyVahrmmZKjB7pAL5rr1SvUxV0DEGnDb0UT7dxa2OicQPVprtGo+tznAUzdjvjg2byvLLXdaWodMM07tJtvYl+gMqWUzgTXIWFeoq42Y99qg/eYOHYbuuCjxHU3vCTVcrNymrXiw01E5Rq2TTcIjtBht6/JXWejBSqOrbZbRCG40lYSSGwOY/QlcYML8WFM7zf5FzzXdQ7pyHqTCtJU+/ycnB2ez7Ojn4Rw/Q==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci
    type: Opaque

