apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mq-client-jks-password
  namespace: dev
spec:
  encryptedData:
    KEY_STORE_PASSWORD: AgA9/CNDHNDB0JEgQijinmu2YktCNGb8bwaPZ3SJjN1CfWeKypvJ3jjlRJCX/59l884geeoNchux/JXkLQROWOShn32hrAQiI0PDcuZ/BpUy8Gw5Ri+HIs5gdPoV4FvgVsnPqU/olpz0dzPnGfg80YInF9SvmWb1c+YDb7ykGSUP1ZmkT977uvPex51DxzzFulx0NuZM35atNyoz9VG+WZlikGIXiZViztJAt9QMiS8ix20TBrqx1ke+CkVujF0vGDAhMMCYCxTNBXQc55d8FoijV9qYJYnSzuprqu4lh2oEB3ahUn/yk7v150Rw52ABjmA2omzdmK81tN1I8wNsyyDG8BUBdADt4Ip4eUxBhI+h8xayN+jQJhnjpC6ayAibWSzpP06S51aJeUIptFyFq7cLdFVwsLRaR5HQZ5vvZDwUbV5DzoIrGc6E5GHAyBeByo+7VqHzFMbOxoQ1mQeI2ZG33wH1NpWuyJZ/7RgV8kH1O9+cslI1Zxz7opjSl1MPwKdBO+J5wT7Q3xDqLp0UQ8M6kKm7uKxZwABsf5+d7a9aW8AqEl+SxHjF1y9md3p4rg4xueHK+eG5ZgJAKe7tlUmyN0/NlKlZQ1v+G59PZZCiutL+uxkPEbCKgr8BM0igHKhsHNI6h+rnaN1WI8aWtssVAQbqrvveqEmiPfde1ssWU6gaGF/pXnJw6vE3Za3mcNORYW+Ar18lEHWAnNUEfQM=
  template:
    metadata:
      creationTimestamp: null
      name: mq-client-jks-password
      namespace: dev

