apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgATq3Ch2Es0zhFi0LNMAyn9g3OQHJZubglnLD/mBHrD9OSLxZ+M51gbcr/mIEmd3VEelqFh52o9H7AcIlJ3lcg0IOSuobvPH0Z7eqMtfx9Ox24rSbM/M9FEuEQ6egTml5e6G+Q3XKsgNiZIsXdxBKyJ2PVuj7cxvKJNsqHlC78FNskRHPCy+KzrGOtbNBMp8ijAjg3uWm6tSWvxYhXOuNx3jD5GUs0gnKR6dJBrWtXr8+60ZGyB0QB2RDGzkfaojsyZMyBLZXftKWBq+WfKelrOHIN13zXgff/vJkSRsDDXfIr6HGM6xH5NNzoLWa779fuvVRqutIO/VmIpDSmjyf1UVw54rMQsbCeRuKliRXccUP7tt+JWHodInca/apZJlxokH4VlSN7OHJJjSo8RcODFF3kPZ5osEzMEQFtfuoH6BE1yba/lcZm5t889t0Fbk0GcVZpyxERNtxmvDhAmW1txM3FdUGjgyODvNBoSkhwi7vphR9xisChRDdPZlCtPAVgvOdXOsX0gVsfw3yEQjL7+t1z6IitZqN2xCmtqiUl1py48qpRjZKCysTkUBuR1ATwXA0hRsoLBzgf8i9Icvfz1eJwU5rMV1v0uHPOxAeGjC7Rx1v0qeb4HiFWksjWMv0R305jy8wL4K2TR51hHnWRVCzQyYfs9Xg7AP/1ZMYTc5BCBIKwuqKER7InWWXB1WTjtoVj7jVek6X9T/FbidHAdcJ35v4a819XpHLu+pievg+cy1JYrH9U9
    username: AgAebc5Ut++U+KCQkmM36VzLUBgWZRd0KodGpITz8jmYTTWZQlHW52s9eSKqN1T6+X0v6AbJWiHfooLridvZh46JHGpJktRLJpQsdsKQx3Jd208gjNRv/9kO3lSgt/OaD8R5jBbS9AT2tpBUJcOFRSukJGEs+DFi5n6WTTt9k64i3xm/sodLTp2hqy/svKyp1WtwB8EQE8YegyBwQIKXZfMfLbnHUaJqOgU7SiOj6glziuSTqQYcoLhsBha/qhXz1CYFoblfrrO7JC29XjMK63jNYR4SfUGKJj3wjTvODHaLRVWWSZznLeL0z2RfqHoVau11b/i9f3vIFyjkYFbtLbEU2fV5zpb6RCJ2hcrq3KeCz2BNYWOQJoWxnLmTtQLrmFVAfXmX/fTJPOccwBZhyVt/0sQU/YeGnmxKX4OyvEJf4McPfrBKRLu8wiJU4pa8XxGoleD4jg8OCldnA9BLs/WmpzKpRiZwNxt1eDaRI4MzCX2iF7igM1RJGNo3id6LPJ6+I2hhOkao7vQ55m1vg76x3d9prVbn39WyqENT3ezdApmY9aV4vxIpdUDXHp0m7Z5JtwuJJMJK+ZT7s0HJGIm9z4r/pW0QPLWIAsVWIeVJwgXvU9fXLu28G92mANb02RriOuA/hblC2+3WRfy1HqOtVlsamjGvyTo9gtYUOFgHXrL05FOe72zLkSUAdfVBjinXt3pTFrM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: git-credentials
      namespace: dev

