apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-instana-agent
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: instana-agent
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 1-infra/namespaces/instana-agent
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: demo-mq-v2-ha-hc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
