apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-secrets
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/instances/namespace-staging/secrets
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: rosa-useast-mq
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true  
