apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-mq-client-cert
spec:
  dnsNames:
    - >-
      *.gitops-sandbox2-6ccd7f378ae819553d37d5f2ee142bd6-0000.tor01.containers.appdomain.cloud
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: CLIENT_SSL_KEY_STORE_PASSWORD
        name: mq-client-jks-password
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  secretName: mq-client-jks
  subject:
    organizations:
    - ibm
