apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mq-client-jks-password
  namespace: dev
spec:
  encryptedData:
    KEY_STORE_PASSWORD: AgCYakVZRhlKutXmf8DYGtgo5ZPAx8GKfLJrSegY1Hp+gc8/u6IzBsEAly6WHV/C14sn7SBdgkxVV8oOs5doBk7Co42X63VxaRloP9IVrZm94M/vmD/DfOHLtgcyU4u61u9bMDghOjZO+ovs5tZ3spa+62mrCARScXEtNGUzVnYwSDD+4/nIf/wBjTpLD2gpVREKpGAOBk56SzBZDd5nME6EMhEzBcqEvKsX6PNHjX7RDD+nKScBynLtJaoqi4eT1idPMEMJ2ZHHIIIIZuymNM4OgsenFekUVam48jMiuB7RO5jB52zjmjJ6syecrKE3vxEaS5Q4d97Hr4rWSLk42mFVt3AWrzrj1asMnOyUPq9r1d6CsOJXUtE1/5XO9qzCfLsyBj5o2BPTNhp139q9MwCwtg6A9hYjHd9oz8D7F3MLanWHYdIhBA8Lb3ttd3O0kgj7B/0ZdBpN15jXgXVFo7LrixH7emKnoKhqWrY2DAP6MGeZmZf0JCAI8hjr2/Mf+VQEViuOr9C1cgokVu8K3kaBIC5QYmdE5GmBdcnrreGitNCvipgSwt52O9MAEz8T3j0zwiwJjdoTc8Y1+Jhuk9LAMK9VyomRgYGwsxyB2E+4II+km/JTBLAwLIag5HxsOrGpVrlOCBMKniuZm5H1/+F4Du+NrKEZzpfWdDarSRa7DUA9WO4dTEcJJ3ClEimiAzlulwGNRXGNyyYrtDynn3M=
  template:
    metadata:
      creationTimestamp: null
      name: mq-client-jks-password
      namespace: dev

