apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: ci-mq-server-cert
spec:
  dnsNames:
    - >-
      *.rosa-east-2.05q1.p1.openshiftapps.com
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  secretName: mq-server-cert
  subject:
    organizations:
    - ibm
