apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: instana-agent
  namespace: instana-agent
spec:
  encryptedData:
    key: AgBi9NJouxoKoY1fE5cOqnWb8k+EO0i6JR7tK6B+7bF4J3ca6lhcDWxWEKEGo6qZ7ttS8n9ppHLVJmkw/yWDfBmni9Yu6giAzxASW7kfhi88agC1iScgK1FFrFwL5eaoS6puTdNDa9hbCJIZ6Z14mEIOPMiFtE/T0N1f6sGZbhkLKxWJH0yuZ1OF8hMmqsZ7VtaCrh/XXsAICwMay7o+RCiKtmOwN0kN7xJZuyHwkpTyiJvkfEhKFMY3oIm/Y2gLaNl38MO7q4FiNjmuwih8Vzc6GVAf8HfPpYLdDLK3oVnpbJY6UokX3s3C6SIM6Wpu+KwyFkhTPoxQPF0wmHXbZRHGuND+pLSJ8gGeIkqxR91IeThgWLv9obSbyhn2Xo3MEU0b6KuTC6BxLgzuNM8gyEzKtO1L6KOfRp4fw0Uyu1+Lf+TkCAO9S3deWSIt7WLoMsdy7e2FRw88xgSY6fCsoG49zhaCQLhsXXq4mXoX4sULDuxZ6Xd31G1ES9NFPDcb2aDIFFh7LNX+oy+8+/tvy3xjmz4XkL+qBxNkXKPrAfkpccn9vj68VB+gXLtDJzP9+P00hmSJPOYbTUjRxquHYyHJ642ojMhjW/BH3nPNSK3hNGyReWaQchvNtZICRpd5AAqNQl9BNHEHhtPJcQVCW2jMPRCm3LP25l2djCHlcvQAJFhgEyUgQsqzoCmeJhU/p4KKtRKGBMBLCYuI
  template:
    metadata:
      creationTimestamp: null
      name: instana-agent
      namespace: instana-agent

