apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: ibm/us-east/toronto1/ocp-clusters/pre-prod-1/2-services/operators/cert-manager
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: demo2-mq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
