apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-mq-prod-instance
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: services
  source:
    path: ibm/us-east/toronto1/ocp-clusters/pre-prod-1/2-services/instances/prod/mq-infra
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: demo2-mq
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    
