apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-secrets
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: services
  source:
    path: ibm/us-east/toronto1/ocp-clusters/pre-prod-1/2-services/instances/staging/secrets
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: demo2-mq
  syncPolicy: {}
