apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-dev
  annotations:
    argocd.argoproj.io/sync-wave: "100"    
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 3-infra/namespaces/dev
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: gitops-sb4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
