apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ci-jks-crt
spec:
  dnsNames:
    - >-
      *.gitops-sandbox2-6ccd7f378ae819553d37d5f2ee142bd6-0000.tor01.containers.appdomain.cloud
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: pwd-key
        name: jks-pass
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  secretName: jks-crt-secret
  subject:
    organizations:
    - ibm
