apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jks-pass
  namespace: ci
spec:
  encryptedData:
    pwd-key: AgC0UUTCnHVh4Iy2DlxCJ+Uz+KmrDO9en6lkk640H9DFYFQLl3YzvVVczcDt8EsmqAl0JkEwU7p2c/LygPfGgShSO5eaD22380vHMGeLN3aY94gB6OF25sUMqiPsvUhZYJsb9QG2ROsVMFFQ8eCuJT65glZ4z3LnTRn/K7Oz/kxZ4OwpxEyzeuEuupVqkYaf7/57/SHjw5aDAdX9scErIarpWMUOW4+FmdfOy53/vlzOXDcf5DddIGXmG/hnMn3D13rCTJdZzhObcSQj/q+U6PpcxZzoCTZMb/6qivxJHWpwuOnRa5vwhPQKyw/IZixI/xGQijmJPl6jiQnR10GFhanE94DF5azi+q3Uxj83o7Bh4fXQDrGNtUT0NbabnX61ABwpLIoULGRQgrNnWDplAL0yUe4ExW1gSf+Tc9jQtdIhwIwUWCJiVBAqAciolV+WikrOjPUGVEj5QZ7E7wbm6thveT7GPumVVAM/XYSqBIMBcayDU70DanB9cJ9FY8xK+M+UBGyNJujMyrAt1FghI6lONCx10NVkDv9FdaM6VhPk8/RgBN8t7qnqKiEaVQnzzgyK4tOufJPcPAhTDqHibHaZz/n/oofi4t/v8okCXDe+up66nRRlfWldA991/vUOEwhdTstx8PDu8JN3MWM9vg2mF+kwXT9aUUA7MIm8LpBcdNTPntam25URV8TaUUKHqDXnK4pgon0mnt8=
  template:
    metadata:
      creationTimestamp: null
      name: jks-pass
      namespace: ci

